// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjGwVKLOKGblyzVPzA9z5ZPHG3HAc-bqk',
    appId: '1:431641178112:web:7502a6251f1c8bbe10e8e5',
    messagingSenderId: '431641178112',
    projectId: 'bas-master',
    authDomain: 'bas-master.firebaseapp.com',
    databaseURL: 'https://bas-master-default-rtdb.firebaseio.com',
    storageBucket: 'bas-master.appspot.com',
    measurementId: 'G-K7F4KVC6L1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDktSADgD91maYu-U78uqUoNwTfToxg5as',
    appId: '1:431641178112:android:9608ece456c0a57310e8e5',
    messagingSenderId: '431641178112',
    projectId: 'bas-master',
    databaseURL: 'https://bas-master-default-rtdb.firebaseio.com',
    storageBucket: 'bas-master.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPND18mgJb1MllgNs0zN7mofwMOzTKG_E',
    appId: '1:431641178112:ios:c8bd35000010e9a010e8e5',
    messagingSenderId: '431641178112',
    projectId: 'bas-master',
    databaseURL: 'https://bas-master-default-rtdb.firebaseio.com',
    storageBucket: 'bas-master.appspot.com',
    iosBundleId: 'com.example.testeagenda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPND18mgJb1MllgNs0zN7mofwMOzTKG_E',
    appId: '1:431641178112:ios:aacb081649815da010e8e5',
    messagingSenderId: '431641178112',
    projectId: 'bas-master',
    databaseURL: 'https://bas-master-default-rtdb.firebaseio.com',
    storageBucket: 'bas-master.appspot.com',
    iosBundleId: 'com.example.testeagenda.RunnerTests',
  );
}
